### ISSUE TITLE
Set listener when open and close intertitials in extension-admob

### ISSUE THREAD

**Issue by ispebo** [openfl/extension-admob#12]
It would be interesting to know at what point is opened and closed interstitials (onAdOpened and onAdClosed) is closed;
They are existing => https://developers.google.com/admob/android/ad-events events

Interstitial sounds and sounds of the game are currently overlap.
It would be nice to hear these events know if i must stop/play game sounds

**Comment by fbricker** [comment]
Done! You can not do:
```haxe
AdMob.onInterstitialEvent = function(event:String){
    trace("Event: "+event);
};
```
Where event is one of this constant STRINGS:
```haxe 
	AdMob.LEAVING
	AdMob.FAILED
	AdMob.CLOSED
	AdMob.DISPLAYING
	AdMob.LOADED
	AdMob.LOADING
```
