### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by ramsestom** [openfl/extension-admob#13]
Here is the error I get when using extension-admob on android 4.1.2 with latest openfl (2.4.0) and lime (2.7.0) and compiled with openfl next mode:

E/dalvikvm( 7256): Could not find class 'android.support.v4.app.NotificationCompat$Builder', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
E/dalvikvm( 7256): Could not find class 'android.support.v4.app.FragmentActivity', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
E/dalvikvm( 7256): Could not find class 'android.support.v4.app.FragmentActivity', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
E/dalvikvm( 7256): Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzap
E/dalvikvm( 7256): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzb
E/dalvikvm( 7256): Could not find class 'android.support.v4.util.SimpleArrayMap', referenced from method com.google.android.gms.ads.internal.zzq.<init>
E/AndroidRuntime( 7256): FATAL EXCEPTION: main
E/AndroidRuntime( 7256): java.lang.NoClassDefFoundError: android.support.v4.util.SimpleArrayMap
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.zzb.<init>(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.zzc.<init>(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.zzf.<init>(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.client.zzz.zzdb(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.client.zzz.zzda(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.internal.client.zzz.zza(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source)
E/AndroidRuntime( 7256):        at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
E/AndroidRuntime( 7256):        at admobex.AdMobEx.reloadBanner(AdMobEx.java:243)
E/AndroidRuntime( 7256):        at admobex.AdMobEx.reinitBanner(AdMobEx.java:226)
E/AndroidRuntime( 7256):        at admobex.AdMobEx.<init>(AdMobEx.java:163)
E/AndroidRuntime( 7256):        at admobex.AdMobEx.getInstance(AdMobEx.java:57)
E/AndroidRuntime( 7256):        at admobex.AdMobEx$1.run(AdMobEx.java:73)
E/AndroidRuntime( 7256):        at android.os.Handler.handleCallback(Handler.java:632)
E/AndroidRuntime( 7256):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 7256):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 7256):        at android.app.ActivityThread.main(ActivityThread.java:4777)
E/AndroidRuntime( 7256):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7256):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 7256):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime( 7256):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime( 7256):        at dalvik.system.NativeStart.main(Native Method)

I checked and I have the latest version of Google Play Services (rev 28) in my SDK manager
Might be a question of correctly defining Support Library import dependencies in your lib: https://developer.android.com/tools/support-library/setup.html

**Comment by fbricker** [comment]
Hi, thanks for reporting... can you check if this happens with lime legacy also?

**Comment by ramsestom** [comment]
Just tested it and yes, the app is also crashing when compiled with legacy. The error message is not exactly the same but really similar (still an error with android.support.v4 probably due to a missing Suport Library dependencies import in your lib) as the one obtained when compiled with next:

E/dalvikvm( 9765): Could not find class 'android.support.v4.util.ArrayMap', referenced from method com.google.android.gms.common.api.GoogleApiClient$Builder.<init>
E/dalvikvm( 9765): Could not find class 'android.support.v4.util.ArrayMap', referenced from method com.google.android.gms.common.api.GoogleApiClient$Builder.zzoI
E/dalvikvm( 9765): Could not find class 'android.support.v4.app.FragmentActivity', referenced from method com.google.android.gms.common.api.GoogleApiClient$Builder.enableAutoManage
E/AndroidRuntime( 9765): FATAL EXCEPTION: main
E/AndroidRuntime( 9765): java.lang.NoClassDefFoundError: android.support.v4.util.ArrayMap
E/AndroidRuntime( 9765):        at com.google.android.gms.common.api.GoogleApiClient$Builder.<init>(Unknown Source)
E/AndroidRuntime( 9765):        at com.google.android.gms.common.api.GoogleApiClient$Builder.<init>(Unknown Source)
E/AndroidRuntime( 9765):        at com.gpgex.GameHelper.createApiClientBuilder(GameHelper.java:238)
E/AndroidRuntime( 9765):        at com.gpgex.GameHelper.setup(GameHelper.java:278)
E/AndroidRuntime( 9765):        at com.gpgex.GooglePlayGames$1.run(GooglePlayGames.java:52)
E/AndroidRuntime( 9765):        at android.os.Handler.handleCallback(Handler.java:632)
E/AndroidRuntime( 9765):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 9765):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 9765):        at android.app.ActivityThread.main(ActivityThread.java:4777)
E/AndroidRuntime( 9765):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9765):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 9765):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime( 9765):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime( 9765):        at dalvik.system.NativeStart.main(Native Method)

**Comment by fbricker** [comment]
hmm... looks like the last version of google-play-services_lib now requires android-support-v4 (i'm testing here and was able to reproduce the issue).

It may take until tomorrow for me to release a new version of this extension adding this fix (as I'm considering making an extension just for android-support-v4 - because many extensions requires this already and I don't want to include the same file many times on one project and cause the APK to grow so much just because of this).

Meanwhile, you can just include extension-facebookads in your project (as this extension contains android-support-v4), so your project should begin to work just be including this extension.

**Comment by ramsestom** [comment]
OK. I am not in a hurry anyway so I will wait for the patched version to be released. Thanks.

**Comment by hpgood** [comment]
android-support-v4.jar add to libs directory ,then the bug will fix.
extension-admob/dependencies/admobex/libs/android-support-v4.jar

**Comment by fbricker** [comment]
Thing is, I do not want to do that since many extensions requires android-support-v4.jar and that will increase your APK weight in some extra MB.
So, I've made an extension named "extension-android-support-v4" which includes this jar in a way it can be used by any extension that requires it (saving some precious MB of your android APK) :)

extension-android-support-v4 is now published and a new version of extension-admob that includes it, will be uploaded in few minutes :+1:

**Comment by fbricker** [comment]
Fixed, extension-admob has been updated on haxelib and github.
Please make sure you have Android Support Library downloaded from your Android SDK Manager.

Thanks for reporting!
