### ISSUE TITLE
Not compatible with latest OpenFL version

### ISSUE THREAD

**Issue by Reintjuu** [openfl/extension-admob#15]
When I create an OpenFL project, include the admob extension and build for Android, I get the following error:
> [aapt] C:\Development\Projects\AdmobTest\Export\android\bin\deps\google-pla
> y-services_lib\res\values-v21\appinvite_styles.xml:5: error: Error retrieving pa
> rent for item: No resource found that matches the given name '@android:style/The
> me.Material.Light.DialogWhenLarge.NoActionBar'.
> 
> BUILD FAILED
> C:\Development\Android SDK\tools\ant\build.xml:597: The following error occurred
>  while executing this line:
> C:\Development\Android SDK\tools\ant\build.xml:649: The following error occurred
>  while executing this line:
> C:\Development\Android SDK\tools\ant\build.xml:694: null returned: 1
> 
> Total time: 3 seconds

Haxelib list contains the following:
> extension-admob: [1.4.7]
> extension-android-support-v4: [1.0.0]
> extension-googleplayservices-lib: [1.1.0]
> openfl: [3.6.0]

I have the latest versions installed in the Android SDK manager of Google Play services and the Android Support Library. Am I doing something wrong or do I need another version of OpenFL?

**Comment by Reintjuu** [comment]
Apparently when adding `<android target-sdk-version="23" if="android" />` to the project.xml it's all magically fixed.

**Comment by NemoStein** [comment]
Just stumbled on the same problem... This should be documented.

**Comment by fbricker** [comment]
Done, not it's documented (this was something google modified on google-play-services and/or android-support-v4 libraries...). I think they're pushing developers to use the last SDK by all means :/
