### ISSUE TITLE
Doesn't Compile With Extension

### ISSUE THREAD

**Issue by esayitch** [openfl/extension-admob#16]
Hi,

After adding <haxelib name="extension-admob"/> to Project.xml, I get the following when trying to compile for Android target:

```
Running Pre-Build Command Line...
cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "Project.xml" android -release -Dfdb

extension-android-support-v4: [** JUST IN CASE NOTICE **] Please remember to download and upgrade 'Android Support V4' on a regular basis. Read more at https://github.com/sempaigames/extension-android-support-v4

extension-googleplayservices-lib: [** JUST IN CASE NOTICE **] Please remember to download and upgrade 'Google Play Services Library' on a regular basis. Read more at https://github.com/sempaigames/extension-googleplayservices-lib
Called from ? line 1
Called from CommandLineTools.hx line 1282
Called from CommandLineTools.hx line 25
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 560
Called from project/PlatformTarget.hx line 60
Called from platforms/AndroidPlatform.hx line 296
Called from /usr/lib/haxe/std/neko/_std/sys/FileSystem.hx line 63
Called from /usr/lib/haxe/std/neko/_std/sys/FileSystem.hx line 54
Uncaught exception - std@sys_file_type
Build halted with errors.

```

I saw that this was an issue here:
https://github.com/openfl/extension-admob/issues/1

But I already have lime 2. Here is my setup:

`actuate: [1.7.5]
admob: git [dev:C:\HaxeToolkit\haxe\lib/admob/git]
extension-admob: [1.4.7]
extension-android-support-v4: [1.0.0]
extension-googleplayservices-lib: [1.1.0]
flixel-addons: [1.1.0]
flixel-demos: [1.1.1]
flixel-templates: [1.0.2]
flixel-tools: [1.0.2]
flixel-ui: [1.0.2]
flixel: 3.3.5 [3.3.6]
haxelib_client: [3.1.0-rc.4]
hxcpp: [3.1.39]
HypGPlay: git [dev:C:\HaxeToolkit\haxe\lib/HypGPlay/git]
inthebox-macros: git [dev:C:\HaxeToolkit\haxe\lib/inthebox-macros/git]
lime: 2.0.0-alpha.6 [2.0.0-alpha.7] 2.0.4
openfl-samples: [2.1.0]
openfl: 2.1.4 [2.1.5] 2.2.1
swf: 1.6.5 1.6.6 [1.8.6]`

And I've both Google Play services and Android Support Library installed.

Any idea what the problem could be? Thanks!

**Comment by fbricker** [comment]
Are you 100% positive that you have google play services lib and android support library v4 installed on the same android sdk that openfl is using?

**Comment by fbricker** [comment]
I'm closing this issue now, if you sill have problems please let me know.
