### ISSUE TITLE
Build not finished

### ISSUE THREAD

**Issue by Stivius** [openfl/extension-admob#20]
Hello, I have an interesting issue.
When I'm trying to compile with that extension, my build cannot be finished. Here is log of my build:

```
extension-android-support-v4: [** JUST IN CASE NOTICE **] Please remember to download and upgrade 'Android Support V4' on a regular basis. Read more at https://github.com/sempaigames/extension-android-support-v4

extension-googleplayservices-lib: [** JUST IN CASE NOTICE **] Please remember to download and upgrade 'Google Play Services Library' on a regular basis. Read more at https://github.com/sempaigames/extension-googleplayservices-lib
Buildfile: C:\Users\maxim\Desktop\DanceCat\export\android\bin\build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 25.1.7
 [checkenv] Installed at C:\Users\maxim\AppData\Local\Android\android-sdk

-setup:
     [echo] Project Name: DanceCat
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 24.0.0 rc4
     [echo] Resolving Build Target for DanceCat...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: C:\Users\maxim\Desktop\DanceCat\export\android\bin\bin\rsObj
    [mkdir] Created dir: C:\Users\maxim\Desktop\DanceCat\export\android\bin\bin\rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for DanceCat...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
```
And without this extension everything is good and build can be finished. So what can cause this weird issue?

**Comment by GregorHaag** [comment]
Try
<android target-sdk-version="23" if="android" />

**Comment by fbricker** [comment]
Please try the target-sdk-version=23 as mentioned by GregorHaag and check if the error is the same.

**Comment by Stivius** [comment]
The error is the same!

**Comment by fbricker** [comment]
Ok, I insisted on that because I see on your log this:
```
[gettarget] API level:        19
```
and google play services requires API version 22 or higher to compile. 

Two questions:
1) Is that the entire compilation log? If not, can you post the entire build log when compilation doesn't finish?
2) Have you installed API level 23 on your android SDK manager before testing this with API LEVEL 23?

**Comment by Stivius** [comment]
1) Yes, it is the entire compilation log.
2) Yes, I have installed it before.

**Comment by Stivius** [comment]
```

extension-android-support-v4: [** JUST IN CASE NOTICE **] Please remember to download and upgrade 'Android Support V4' on a regular basis. Read more at https://github.com/sempaigames/extension-android-support-v4

extension-googleplayservices-lib: [** JUST IN CASE NOTICE **] Please remember to download and upgrade 'Google Play Services Library' on a regular basis. Read more at https://github.com/sempaigames/extension-googleplayservices-lib
 - Link : libApplicationMain-debug-v7.so
C:/Development/Android NDK/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld.exe: Warning: C:\Development\Android NDK/platforms/android-9/arch-arm/usr/lib/crtbegin_so.o: Unknown EABI object attribute 44
Buildfile: C:\Users\maxim\Desktop\DanceCat\export\android\bin\build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 25.1.7
 [checkenv] Installed at C:\Users\maxim\AppData\Local\Android\android-sdk

-setup:
     [echo] Project Name: DanceCat
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 24.0.0 rc4
     [echo] Resolving Build Target for DanceCat...
[gettarget] Project Target:   Android 6.0
[gettarget] API level:        23
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for DanceCat...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:

[Finished in 82.1s]
```

This the enitre log with target-sdk-version=23.

**Comment by fbricker** [comment]
Just in case: Do wich version of google play services do you have installed on your android sdk manager?

If it's version 30 or higher, check this: https://github.com/SempaiGames/extension-googleplayservices-lib/issues/3

**Comment by Stivius** [comment]
The link on 29 revision is unavailable.

**Comment by fbricker** [comment]
So I assume you have version 30 installed, right?

About the broken link: Seems like google removed that file... If you find another link that's still working please let me know so I can upgrade the other post.

**Comment by vega-7** [comment]
Hi Stivius , i was dealing with the same trouble , turns out this  occurs  cause the include.xml file of the extension, is bad reference to the the correct path of the google play service folder, you have to this, if you already follow this link https://github.com/SempaiGames/extension-googleplayservices-lib/issues/3 ( follow this link is really crucial )

Solution 1
Rename the folder google-play-services  to google_play_services  

Solution 2
Go to \YOUR HaxeToolkit PATH\haxe\lib\extension-googleplayservices-lib\1,1,0\include.xml and edit the path attribute on the line 8,. the line that says { dependency name="google-play-services_lib" path="the path to you google play service folder" /}  hope this helps.

**Comment by Stivius** [comment]
Hi, I have this in my include.xml:
```
<haxelib name="extension-android-support-v4" /> 
<haxelib name="extension-googleplayservices-lib" /> 
```
..and I have installed these libs.

**Comment by fbricker** [comment]
Sorry to insist, but:
Can you confirm which version of google play services you have installed on your android sdk manager?

**Comment by Stivius** [comment]
30.
But your link does not work.

**Comment by fbricker** [comment]
I see, this **won't work with version 30** _(as explained here: https://github.com/SempaiGames/extension-googleplayservices-lib/issues/3)_

So, **you need to go back to version 29**. I understand that link doesn't work any more (looks like google removed that file...) So, **you'll need to find it somewhere else**, or just wait until someone finds it and publish a working link.
