### ISSUE TITLE
Setting tagForChildDirectedTreatment(true) for COPPA Compliance

### ISSUE THREAD

**Issue by Netforza** [openfl/extension-admob#25]
Is it possible to tag the adverts for child-directed treatment.
This is needed for COPPA Compliance in apps and games for kids?

Here is the explication how to do it in the sdk: https://firebase.google.com/docs/admob/android/targeting#child-directed_setting

**Comment by fbricker** [comment]
Done, version 1.6.4 released adding COPPA support.

```haxe
        // if your app is for children and you want to enable the COPPA policy,
        // you need to call tagForChildDirectedTreatment(), before calling INIT.
        AdMob.tagForChildDirectedTreatment();
```
