### ISSUE TITLE
Support for Admob rewarded video

### ISSUE THREAD

**Issue by stein-D** [openfl/extension-admob#27]
Hi, 

Can you guys support for admob rewarded video feature?

Thanks.

**Comment by fbricker** [comment]
Hi, as rewarded video is offered only through mediation in admob, we're working together mediation and rewarded videos:

Said so, there's currently a branch for that. You can see it here:
https://github.com/openfl/extension-admob/tree/mediation

Also, we're discussing this here: https://github.com/openfl/extension-admob/issues/19

I'm closing this issue now. Please keep the thread on the other issue.

Thanks!
